import "./globals.css";
import type { Metadata } from "next";

import { Amplify, API, Auth, withSSRContext } from "aws-amplify";
import awsmobile from "../aws-exports";

Amplify.configure({ ...awsmobile, ssr: true });

export const metadata: Metadata = {
  title: "Quote Generator",
  description: "Generated by create next.js ver13",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  );
}
